version: "3"

services:
  loader:
    container_name: "loader-api"
    ports:
      - "90:8080"
    depends_on:
      - "mongodb"
      - "chromium"
    environment:
      ICONS_PATH: /icons
    build:
      context: ./src/loader_api
      volumes: ./assets/icons:/icons

  mongodb: 
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata/db:/data/db

  chromium:
    ports:
      - "9222:9222"
    build:
      context: ./src/chromium


